# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/0981f787-9cb2-495e-95d5-611e0de24d85";
      fsType = "btrfs";
      options = [ "subvol=@nixos-root" "compress-force=zstd" ];
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/1AC9-E1AD";
      fsType = "vfat";
    };

  fileSystems."/mnt/btrfs" =
    {
      device = "/dev/disk/by-uuid/0981f787-9cb2-495e-95d5-611e0de24d85";
      fsType = "btrfs";
      options = [ "subvol=/" ];
    };

  fileSystems."/mnt/hdd" =
    {
      device = "/dev/disk/by-uuid/beccaf7e-9c7e-4c04-959b-52f1e0375491";
      fsType = "ext4";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/d94babc9-ef09-43bb-949d-ed477ff4f4c2";
      fsType = "ext4";
    };

  fileSystems."/opt/games" =
    {
      device = "/dev/disk/by-uuid/0981f787-9cb2-495e-95d5-611e0de24d85";
      fsType = "btrfs";
      options = [ "subvol=@steamgames" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b7ec8c05-2a36-4b35-99fc-866e97c6330b"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
